alias ls='ls -lha'
alias space='df -aTh'
alias home='cd ~'
alias keygen='ssh-keygen -t rsa -b 4096'
alias gpg='gpg2'
alias publicip='dig +short myip.opendns.com @resolver2.opendns.com'
alias lsblk='lsblk -f'
